source 'https://github.com/CocoaPods/Specs.git'

target :'SYSegmentedControlExample-tvOS' do
	platform :tvos, '9.0'
	pod 'SYKit'
end

target :'SYSegmentedControlExample-iOS' do
	platform :ios, '8.0'
	pod 'SYKit'
end


